### ISSUE TITLE
unnecessary dependency on debug

### ISSUE THREAD

**Issue by lucasvickers** [tj/jog#11]
In FileStore you depend on debug
is this a necessary dependency?

https://npmjs.org/package/websocket claims you have no dependencies

**Comment by lucasvickers** [comment]
Same for redis, your code should not explicitly include this if it's not being used

**Comment by tj** [comment]
debug is not going away, but we could remove the redis dep and make the user pass a redis client

**Comment by lucasvickers** [comment]
thanks for the quick response.  ps I really like the idea of forcing json logging, makes parsing a lot easier!  good stuff

**Comment by cpsubrian** [comment]
#13 and #14 probably closes this right?
