### ISSUE TITLE
handling Error instances

### ISSUE THREAD

**Issue by danmilon** [tj/jog#6]
Hello!

I am trying to use a simple logging library for some node app. Mainly log about various errors that are returned from async functions, so that i can find out more later. (eg http request timeout).

What i thought is something like

```
async(function (err, res) {
  if (err) {
    log.error('async failed', {error: err})
  }
}
```

so that i can later inspect the error, and maybe a stack trace.
The problem is that jog does not know how to handle `Error` instances.
I guess checking if a value of the passed object is `instanceof Error`, then replace it with `err.stack`.

Do you think this should be implemented at the logging library level?

**Comment by tj** [comment]
I'm impartial, it could be:

``` js
log.error('fail', err)
log.error('fail', { error: err })
log.error('fail', { error: err.stack })
```

doesn't really matter to me

**Comment by danmilon** [comment]
What do you think about this? If it is ok I should write the docs.

**Comment by tj** [comment]
it's a pretty high-traffic method, we would probably be best (if anything) to just do:

``` js
if (obj.error instanceof Error) obj.error = obj.error.stack;
```

**Comment by tj** [comment]
(err.stack includes the message) or we could add `.message` explicitly as well, probably wouldn't hurt

**Comment by danmilon** [comment]
For future reference, see #20, closing.
